module.exports = {
  enum: [
    'API',
    'FORM',
    'IMPORT',
    'ANALYTICS',
    'SALESFORCE',
    'CONTACTS_WEB',
    'CRM_UI',
    'MOBILE_IOS', 'MOBILE_ANDROID',
    'EMAIL',
    'WORKFLOWS',
    'SOCIAL',
    'COMPANIES',
    'DEALS',
    'ENGAGEMENTS',
    'INTEGRATION', 'INTEGRATIONS_PLATFORM',
    'MERGE_CONTACTS',
    'MERGE_COMPANIES ',
    'SALES', 'SIGNALS', 'SIDEKICK',
    'LEADIN',
    'BCC_TO_CRM', 'FORWARD_TO_CRM',
    'GMAIL_INTEGRATION',
    'SEQUENCES',
    'CALCULATED',
    'MIGRATION', 'WAL_INCREMENTAL', 'TASK', 'BATCH_UPDATE', 'BIDEN', 'DEFAULT', 'ASSISTS', 'PORTAL_USER_ASSOCIATOR', 'HEISENBERG', 'ACADEMY', 'SALES_MESSAGES', 'AVATARS_SERVICE', 'COMPANY_FAMILIES'
  ]
};
